AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'coverage/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'lib/generators/templates/**/*'
    - 'lib/generators/ai_models/templates/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'lib/ai_models/providers/ollama.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'ai_models.gemspec'

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'lib/ai_models/providers/ollama.rb'

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/ai_models/providers/ollama.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/ai_models/providers/ollama.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/ai_models/errors.rb'

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false